apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: metallb-advertisment
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-pool 
  aggregationLength: 32
  localPref: 100
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: bgppeer-10.0.0.254
  namespace: metallb-system
spec:
  myASN: 64512
  peerASN: 64513
  peerAddress: 10.0.0.254