kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner-ssd
  namespace: pv-nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-client-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner-ssd
          image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          resources:
            limits:
              cpu: "0.1"
              memory: 100Mi
          volumeMounts:
            - name: nfs-client-ssd
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: ff1.dev/ssd
            - name: NFS_SERVER
              value: 10.0.0.2
            - name: NFS_PATH
              value: /ssd01
      volumes:
        - name: nfs-client-ssd
          nfs:
            server: 10.0.0.2
            path: /ssd01

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner-hdd
  namespace: pv-nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-client-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner-hdd
          image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          resources:
            limits:
              cpu: "0.1"
              memory: 100Mi
          volumeMounts:
            - name: nfs-client-hdd
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: ff1.dev/hdd
            - name: NFS_SERVER
              value: 10.0.0.2
            - name: NFS_PATH
              value: /hdd01

      volumes:
        - name: nfs-client-hdd
          nfs:
            server: 10.0.0.2
            path: /hdd01
